@api = http://localhost:4000/auth

###
POST {{api}}/register
Content-Type: application/json

{
    "username":"juanita",
    "email":"juani@example.org",
    "password":"123",
    "type_of_rol":"",
    "profile":""
    
}