@api = http://localhost:4000

###
POST {{api}}/mormedi/clients
Content-Type: application/json


{
  "name":"neymi",
  "lastname":"ssss",
  "qualification":"c",
  "department":"meta",
  "company":"face",
  "telephone":12345,
  "address":"asd" ,
  "postal_code":123,   
  "city":"aaa",       
  "comments":"mm"    

  
}

